### ISSUE TITLE
Får 500 error når jeg burde fått 404

### ISSUE THREAD

**Issue by Kristandre** [vektorprogrammet/webpage#59]
http://vektorprogrammet.no/tull fører til 500 Internal Server Error

**Comment by rubenrav** [comment]
Oops sikkert min feil

**Comment by rubenrav** [comment]
Ser muligens ut som om at feilen kom etter oppdateringen av base.html.twig. Det er noe med Exceptions som for eksempel gjør at vi bør ha app.user i is_granted if'ene. Skal teste det i morgen.
