### ISSUE TITLE
lateAdmission - kan ikke velge fieldOfStudy og Semester i utfyllingsskjema

### ISSUE THREAD

**Issue by vegardbb** [vektorprogrammet/webpage#72]
![lateadmissue](https://cloud.githubusercontent.com/assets/11057203/12162875/fbf77386-b507-11e5-93a1-c70800a2ec13.png)

Skjermdump viser spørringer gjort av Doctrine.

**Comment by Kristandre** [comment]
Funksjonen for lateAdmission har blitt implementert.
